# refs: https://docs.gitlab.com/ee/ci/yaml/index.html
# refs: https://doc.rust-lang.org/cargo/guide/continuous-integration.html#gitlab-ci
image: rustlang/rust:nightly
# image: rust/latest

stages:
  - build
  - test
  - deploy

nightly-build:
  stage: build
  before_script: 
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends build-essential
  script:
    - rustc --version && cargo --version
    - cargo build --verbose

nightly-test:
  stage: test
  script:
    - rustc --version && cargo --version
    - cargo test --workspace --verbose