# refs: https://docs.gitlab.com/ee/ci/yaml/index.html
# refs: https://doc.rust-lang.org/cargo/guide/continuous-integration.html#gitlab-ci
image: rustlang/rust:nightly
# image: rust/latest

stages:
  - build
  - test
  - deploy

before_script: 
  - mkdir -p /.cargo
  - echo -e "[source]\n[source.crates-io]\nreplace-with = 'tuna'\n\n[source.tuna]\nregistry = \"https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git\"" >> /.cargo/config.toml
  - cat /.cargo/config.toml
  - sed -i "s@http://deb.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list && rm -Rf /var/lib/apt/lists/* && apt-get update -yqq
  - cat /etc/apt/sources.list
  - apt-get install -yqq --no-install-recommends build-essential


nightly-build:
  stage: build
  script:
    - rustc --version && cargo --version
    - cargo build --verbose

nightly-test:
  stage: test
  script:
    - rustc --version && cargo --version
    - cargo test --workspace --verbose