[package]
name = "parsing_rs"
version = "0.3.2"
edition = "2018"
repository = "https://gitee.com/BoleanTech/parsing-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
nom = "6.1.2"
# needed by parsing_pcap example
pcap-parser = "0.11.1"
colored = "2"
walkdir = "2.3.2"