[package]
name = "parsing-rs"
version = "0.1.0"
authors = ["starliiit <esu.eru.sl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "protocols"
]

[dependencies]
protocols = {path = "protocols"}
pcap-parser = "0.11.1"

[[example]]
name = "pcap_tester"
path = "examples/pcap_tester.rs"