[package]
name = "parsing_rs"
version = "0.3.2"
edition = "2018"
repository = "https://gitee.com/BoleanTech/parsing-rs"

[workspace]
exclude = ["benches"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
nom = "6.1.2"

[dev-dependencies]
# required by parsing_pcap example and parsing bench
pcap-parser = "0.11.1"
colored = "2"
walkdir = "2.3.2"